<script type="text/javascript">
<?php
// values from config.ini
echo 'var map_default_zoom = ' . $this->default_zoom . ";\n";
echo 'var map_default_long = ' . $this->default_long . ";\n";
echo 'var map_default_lat = ' . $this->default_lat . ";\n";
echo 'var map_max_zoom = ' . $this->max_zoom . ";\n";
echo 'var map_min_zoom = ' . $this->min_zoom . ";\n";

echo 'var map_show_host = "' . $this->host . "\";\n";

$mapId = uniqid();
echo 'var id = "'.$mapId."\";\n";

?>
</script>
<div class="controls">
<?php if (! $this->compact): ?>
<?= $this->tabs ?>
<?php endif ?>
</div>
<div class="content">
<div id="map-<?php echo $mapId; ?>" class="map<?php if ($this->compact): ?>
 compact
<?php endif ?>"></div>
</div>
