<script type="text/javascript">
<?php
$mapId = uniqid();
echo 'var id = "'.$mapId."\";\n";
echo 'var map_default_zoom = ' . $this->default_zoom . ";\n";
echo 'var map_default_long = ' . $this->default_long . ";\n";
echo 'var map_default_lat = ' . $this->default_lat . ";\n";
echo 'var map_max_zoom = ' . $this->max_zoom . ";\n";
echo 'var map_min_zoom = ' . $this->min_zoom . ";\n";

echo 'var map_show_host = "' . $this->host . "\";\n";
?>
var service_status = {};
service_status[0] = '<?= $this->translate('OK', 'icinga.state') ?>';
service_status[1] = '<?= $this->translate('WARNING', 'icinga.state') ?>';
service_status[2] = '<?= $this->translate('CRITICAL', 'icinga.state') ?>';
service_status[3] = '<?= $this->translate('UNKNOWN', 'icinga.state') ?>';
service_status[99] = '<?= $this->translate('PENDING', 'icinga.state') ?>';
</script>
<div class="controls">
<?php if (! $this->compact): ?>
<?= $this->tabs ?>
<?php endif ?>
</div>
<div class="content">
<div <?=($this->compact ? 'style="height:'.$this->dashletHeight.'px;" ' : ""); ?>id="map-<?php echo $mapId; ?>" class="map<?php if ($this->compact): ?>
 compact
<?php endif ?>"></div>
</div>
